Repository oracle-samples/microtx-samples, pull requests merged in 2024-05, with the labels that each got.

#32 Helidon and Springboot based sample apps with Oracle Transaction event Queue(TEQ) integration
  xa/java/jms/department-helidon-teq/Database_Wallet/README.txt
  xa/java/jms/department-helidon-teq/Dockerfile
  xa/java/jms/department-helidon-teq/department.sql
  xa/java/jms/department-helidon-teq/pom.xml
  xa/java/jms/department-helidon-teq/readme.md
  xa/java/jms/department-helidon-teq/src/main/java/com/oracle/mtm/sample/Configuration.java
  xa/java/jms/department-helidon-teq/src/main/java/com/oracle/mtm/sample/data/AccountsService.java
  xa/java/jms/department-helidon-teq/src/main/java/com/oracle/mtm/sample/data/IAccountsService.java
  xa/java/jms/department-helidon-teq/src/main/java/com/oracle/mtm/sample/entity/Account.java
  xa/java/jms/department-helidon-teq/src/main/java/com/oracle/mtm/sample/resource/AccountsResource.java
  xa/java/jms/department-helidon-teq/src/main/resources/META-INF/beans.xml
  xa/java/jms/department-helidon-teq/src/main/resources/META-INF/helidon/serial-config.properties
  xa/java/jms/department-helidon-teq/src/main/resources/META-INF/microprofile-config.properties
  xa/java/jms/department-helidon-teq/src/main/resources/WEB/index.html
  xa/java/jms/department-helidon-teq/src/main/resources/application.yaml
  xa/java/jms/department-helidon-teq/src/main/resources/logging.properties
  xa/java/jms/department-helidon-teq/src/main/resources/tmm.properties
  xa/java/jms/department-spring-teq/Database_Wallet/README.txt
  xa/java/jms/department-spring-teq/Dockerfile
  xa/java/jms/department-spring-teq/department.sql
  xa/java/jms/department-spring-teq/pom.xml
  xa/java/jms/department-spring-teq/readme.md
  xa/java/jms/department-spring-teq/src/main/java/com/oracle/mtm/sample/DepartmentSpringApplication.java
  xa/java/jms/department-spring-teq/src/main/java/com/oracle/mtm/sample/XADataSourceConfig.java
  xa/java/jms/department-spring-teq/src/main/java/com/oracle/mtm/sample/data/AccountService.java
  xa/java/jms/department-spring-teq/src/main/java/com/oracle/mtm/sample/data/IAccountService.java
  xa/java/jms/department-spring-teq/src/main/java/com/oracle/mtm/sample/entity/Account.java
  xa/java/jms/department-spring-teq/src/main/java/com/oracle/mtm/sample/resource/AccountsResource.java
  xa/java/jms/department-spring-teq/src/main/resources/application.yaml
  xa/java/jms/department-spring-teq/src/main/resources/logback-spring.xml
Labels: enhancement, OCA Required

#34 OpenShift LRA sample app helmchart fix
  README.md
  lra/helmcharts/sampleappslra-lockfree/Chart.yaml
  lra/helmcharts/sampleappslra/Chart.yaml
  lra/helmcharts/sampleappslraspring-istio-openshift/.helmignore
  lra/helmcharts/sampleappslraspring-istio-openshift/Chart.yaml
  lra/helmcharts/sampleappslraspring-istio-openshift/Readme.md
  lra/helmcharts/sampleappslraspring-istio-openshift/templates/_helpers.tpl
  lra/helmcharts/sampleappslraspring-istio-openshift/templates/networking.yaml
  lra/helmcharts/sampleappslraspring-istio-openshift/templates/sampleappslraspring.yaml
  lra/helmcharts/sampleappslraspring-istio-openshift/values.yaml
  lra/helmcharts/sampleappslraspring/Chart.yaml
  tcc/java/helmcharts/sampleappstcc/Chart.yaml
  tcc/nodejs/helmcharts/sampleappstccnode/Chart.yaml
  tcc/python/helmcharts/sampleappstccpy/Chart.yaml
  xa/java/department-helidon/javax/beans.xml
  xa/java/department-helidon/javax/pom.xml
  xa/java/department-helidon/javax/readme.md
  xa/java/helmcharts/ords-teller/Chart.yaml
  xa/java/helmcharts/transfer-multiplerm/Chart.yaml
  xa/java/helmcharts/transfer-nonxa-mongodb/Chart.yaml
  xa/java/helmcharts/transfer-nonxa-mysql/Chart.yaml
  xa/java/helmcharts/transfer-teller-as-participant-nonxa-ds/Chart.yaml
  xa/java/helmcharts/transfer-teller-as-participant/Chart.yaml
  xa/java/helmcharts/transfer-transaction-promotion/Chart.yaml
  xa/java/helmcharts/transfer/Chart.yaml
  xa/java/teller/javax/Dockerfile
  xa/java/teller/javax/beans.xml
  xa/java/teller/javax/pom.xml
  xa/java/teller/javax/readme.md
  xa/nodejs/helmcharts/transfer/Chart.yaml
  xa/plsql/databaseapp/enable_ords.sql
  xa/plsql/databaseapp/ords_initiator_app.sql
  xa/plsql/databaseapp/ords_participant_app.sql
Labels: OCA Verified

#37 Update node.js samples with renamed library
  lra/lrademo/flight/Dockerfile
  lra/lrademo/flight/package.json
  lra/lrademo/flight/readme.md
  lra/lrademo/flight/src/routes/flight.ts
  lra/lrademo/flight/tmmlib-node-23.4.2.tgz
  tcc/nodejs/flight/Dockerfile
  tcc/nodejs/flight/package.json
  tcc/nodejs/flight/readme.md
  tcc/nodejs/flight/src/flight.ts
  tcc/nodejs/flight/tsconfig.json
  tcc/nodejs/hotel/Dockerfile
  tcc/nodejs/hotel/package.json
  tcc/nodejs/hotel/readme.md
  tcc/nodejs/hotel/src/hotel.ts
  tcc/nodejs/hotel/tsconfig.json
  tcc/nodejs/travel-agent/Dockerfile
  tcc/nodejs/travel-agent/package.json
  tcc/nodejs/travel-agent/readme.md
  tcc/nodejs/travel-agent/src/travelagent.ts
  tcc/nodejs/travel-agent/tsconfig.json
  xa/nodejs/department/Dockerfile
  xa/nodejs/department/package.json
  xa/nodejs/department/readme.md
  xa/nodejs/department/src/department.ts
  xa/nodejs/department/tsconfig.json
  xa/nodejs/teller/Dockerfile
  xa/nodejs/teller/package.json
  xa/nodejs/teller/readme.md
  xa/nodejs/teller/src/accounts.ts
  xa/nodejs/teller/tsconfig.json
Labels: OCA Verified

#38 LRA Lock Free reservation issues fix due to quotes and missing dependency
  lra/lockfree/springboot/flight-springboot/pom.xml
  lra/lockfree/springboot/flight-springboot/src/main/resources/application.properties
  lra/lockfree/springboot/hotel-springboot/pom.xml
  lra/lockfree/springboot/hotel-springboot/src/main/resources/application.properties
  lra/lockfree/springboot/trip-manager-springboot/src/main/resources/application.properties
Labels: OCA Verified

#39 Oracle TEQ integration and permission issues fix
  xa/java/jms/department-helidon-teq/department.sql
  xa/java/jms/department-helidon-teq/src/main/java/com/oracle/mtm/sample/Configuration.java
  xa/java/jms/department-helidon-teq/src/main/java/com/oracle/mtm/sample/data/AccountsService.java
  xa/java/jms/department-helidon-teq/src/main/resources/application.yaml
  xa/java/jms/department-spring-teq/department.sql
  xa/java/jms/department-spring-teq/src/main/java/com/oracle/mtm/sample/XADataSourceConfig.java
  xa/java/jms/department-spring-teq/src/main/java/com/oracle/mtm/sample/data/AccountService.java
  xa/java/jms/department-spring-teq/src/main/resources/application.yaml
Labels: OCA Verified

#40 Lockfree reservation helmchart issue fix
  lra/helmcharts/sampleappslra-lockfree/templates/sampleappslra.yaml
Labels: OCA Verified

#43 Micronaut LRA resilience issues fix
  lra/lrademo/micronaut/trip-manager-micronaut/src/main/java/com/example/tripmanager/TripManagerResource.java
  lra/lrademo/micronaut/trip-manager-micronaut/src/main/java/com/example/tripmanager/TripService.java
Labels: OCA Verified

#42 Set max count issue fix in lockfree hotel & flight apps
  lra/lockfree/springboot/flight-springboot/src/main/java/com/example/flightsb/FlightResource.java
  lra/lockfree/springboot/flight-springboot/src/main/java/com/example/flightsb/FlightService.java
  lra/lockfree/springboot/hotel-springboot/src/main/java/com/example/hotelsb/HotelResource.java
  lra/lockfree/springboot/hotel-springboot/src/main/java/com/example/hotelsb/HotelService.java
Labels: OCA Verified

#36 Non Transactinal connection Injection
  xa/java/department-helidon-jpa/src/main/java/com/oracle/mtm/sample/data/AccountsService.java
  xa/java/department-helidon/src/main/java/com/oracle/mtm/sample/data/AccountsService.java
  xa/java/department-nonxa-ds/src/main/java/com/oracle/mtm/sample/data/AccountsService.java
  xa/java/department-spring-jpa-multiplerm-postgres/pom.xml
  xa/java/department-spring-jpa-multiplerm/pom.xml
  xa/java/department-spring-jpa/pom.xml
  xa/java/department-spring-jpa/src/main/java/com/oracle/mtm/sample/XADataSourceConfig.java
  xa/java/department-spring-jpa/src/main/java/com/oracle/mtm/sample/data/AccountService.java
  xa/java/department-spring-jpa/src/main/java/com/oracle/mtm/sample/data/CustomAccountRepository.java
  xa/java/department-spring/src/main/java/com/oracle/mtm/sample/data/AccountService.java
  xa/java/teller-as-participant-spring/pom.xml
Labels: OCA Required

#44 TripClient NPE fix with proper error message
  lra/lrademo/trip-client/src/main/java/TripClient.java
Labels: OCA Verified
